"""
inverse_design.py
==================
Constructive solution to the "Automorphism Design" problem of Sec. 3.4:
given a target ring automorphism (or a set of them, generating a subgroup
Gamma <= Aut(R_{l,m})), build a BB code (A,B) that is *provably* invariant
under Gamma -- not by search, but by construction.

The trick (an explicit instance of Lemma 3.7 / Theorem 3.5's "generators
differ by a unit" with the unit taken to be w=1 on the nose):

    If S subset Z_l x Z_m is a union of full Gamma-orbits, then
    phi(sum_{(i,j) in S} x^i y^j) = sum_{(i,j) in S} x^i y^j   for every
    phi in Gamma, i.e. psi(A) = A *exactly*, not just up to a unit.

So: pick seed monomials, close them under the target group to get an
orbit-closed support S, and set A = sum(S). This guarantees a genuine code
automorphism (Corollary 3.6 with w=1) for every phi in Gamma.

A second, complementary trick uses the antipode:  since every automorphism
in our catalog is a *linear* map on the exponent lattice Z_l x Z_m, and bar
= -Id is central in GL_2, we always have  phi . bar = bar . phi.  Hence if
A is Gamma-orbit-closed, so is bar(A).  Setting B := bar(A) therefore gives,
*for free*, simultaneously:
    (a) a ring-level code automorphism for every phi in Gamma (Cor. 3.6,
        w=1, since phi(A)=A and phi(B)=phi(bar(A))=bar(phi(A))=bar(A)=B), and
    (b) a stabilizer-level "Hadamard-fold" symmetry (swap A<->B composed
        with bar), because bar(A)=B and bar(B)=bar(bar(A))=A means the pair
        (A,B) is fixed by "apply bar to both slots, then swap them".

This module builds one worked example per catalog symmetry (multiplier,
partial fold, full fold, shear, transpose), one example combining several
symmetries into a single code (a genuine sub-group of automorphisms), and
one example in the previously-uncovered "mixed" (one even, one odd) CRT
regime, then *verifies every claim computationally* using the same
detection routines used on the forward-problem benchmark codes.
"""
from __future__ import annotations
from typing import List
import numpy as np

from bb_ring import (
    Ring, RingAuto, identity_auto, multiplier, theta_x, theta_y, full_fold,
    transpose_auto, shear_family, full_catalog, generate_group,
)
from bb_code import BBCode
from bb_automorphisms import (
    test_code_automorphism, test_stabilizer_symmetry, scan_code_automorphisms,
    scan_stabilizer_symmetries, GBLOCK_CATALOG,
)


# ============================================================================
#  Group closure / orbit machinery
#  (generate_group itself now lives in bb_ring.py, shared verbatim with the
#  forward-problem catalog builder full_catalog -- see module docstring.)
# ============================================================================

def group_closure(generators: List[RingAuto], ell: int, m: int) -> List[RingAuto]:
    return generate_group(generators, ell, m)


def orbit_closed_terms(seeds: List[tuple], group: List[RingAuto], ell: int, m: int) -> set:
    S = set()
    for s in seeds:
        s = (s[0] % ell, s[1] % m)
        S |= {(phi.map(*s)[0] % ell, phi.map(*s)[1] % m) for phi in group}
    return S


def build_orbit_poly(ring: Ring, seeds: List[tuple], generators: List[RingAuto]) -> np.ndarray:
    group = group_closure(generators, ring.ell, ring.m)
    S = orbit_closed_terms(seeds, group, ring.ell, ring.m)
    return ring.from_terms(list(S))


# ============================================================================
#  Verification helper
# ============================================================================

def verify_group_invariance(ring: Ring, code: BBCode, generators: List[RingAuto],
                             expect_swap: bool = False) -> None:
    """Check that *every* element of the group generated by `generators` is
    detected as a ring-level code automorphism of `code` (Cor. 3.6, w=1
    guaranteed by construction, but we verify via the same rowspace test
    used for the forward benchmarks, exactly as an outside verifier would)."""
    group = group_closure(generators, ring.ell, ring.m)
    ok_count = 0
    for phi in group:
        ok, _ = test_code_automorphism(ring, code, phi, swap_AB=expect_swap)
        ok_count += int(ok)
    print(f"    verified: {ok_count}/{len(group)} group elements confirmed as "
          f"code automorphisms (swap_AB={expect_swap})")
    assert ok_count == len(group), "construction failed to be group-invariant!"


def summarize(name: str, ring: Ring, code: BBCode) -> None:
    print(f"  -> {code.params_str()}   A={ring.poly_str(code.A)}   B={ring.poly_str(code.B)}")
    d = code.min_distance_bruteforce()
    if d is not None:
        print(f"     distance (bruteforce) = {d}")


# ============================================================================
#  Worked examples
# ============================================================================

def example_multiplier():
    print("\n[1] SINGLE SYMMETRY: multiplier psi_(2,2), ell=7, m=3")
    ring = Ring(7, 3)
    psi = multiplier(7, 3, 2, 2)   # order lcm(ord_7(2), ord_3(2)) = lcm(3,2) = 6
    A = build_orbit_poly(ring, [(1, 1), (0, 2)], [psi])
    B = build_orbit_poly(ring, [(2, 0)], [psi])
    code = BBCode(ring, A, B, name="mult_demo")
    summarize("mult", ring, code)
    verify_group_invariance(ring, code, [psi])
    return ring, code


def example_partial_fold():
    print("\n[2] SINGLE SYMMETRY: partial fold theta_x, ell=5, m=4")
    ring = Ring(5, 4)
    th = theta_x()
    A = build_orbit_poly(ring, [(1, 1)], [th])
    B = build_orbit_poly(ring, [(2, 3)], [th])
    code = BBCode(ring, A, B, name="thetax_demo")
    summarize("theta_x", ring, code)
    verify_group_invariance(ring, code, [th])
    return ring, code


def example_full_fold_and_hadamard():
    print("\n[3] SINGLE SYMMETRY: full fold iota (antipode), ell=9, m=5"
          "\n    + FREE bonus symmetry: B := bar(A) also gives a Hadamard-fold"
          " (swap+bar) stabilizer symmetry")
    ring = Ring(9, 5)
    A = ring.from_terms([(1, 0), (0, 2)])
    B = ring.bar(A)
    code = BBCode(ring, A, B, name="fold_demo")
    summarize("iota", ring, code)
    iota = full_fold()
    # Corollary 3.6 with swap: iota(A,B) should equal swap(A,B) exactly (w=1)
    ok, info = test_code_automorphism(ring, code, iota, swap_AB=True)
    print(f"    iota with A<->B swap detected as code automorphism: {ok}")
    assert ok
    # Also check as a full stabilizer-level Hadamard-fold symmetry (Thm 3.2)
    hits = scan_stabilizer_symmetries(ring, code, include_shears=False)
    had_hits = [h for h in hits if "Hadamard" in h["gblock"]]
    print(f"    stabilizer-level Hadamard-fold hits found: {len(had_hits)}")
    return ring, code


def example_shear():
    print("\n[4] SINGLE SYMMETRY: shear x -> x y^3, ell=12, m=6 "
          "(the outline's own example, d=gcd(12,6)=6)")
    ring = Ring(12, 6)
    shears = shear_family(12, 6)
    sh3 = [s for s in shears if "c=3" in s.name][0]
    A = build_orbit_poly(ring, [(1, 0), (1, 1)], [sh3])
    B = build_orbit_poly(ring, [(2, 0), (0, 1)], [sh3])
    code = BBCode(ring, A, B, name="shear_demo")
    summarize("shear", ring, code)
    verify_group_invariance(ring, code, [sh3])
    return ring, code


def example_transpose():
    print("\n[5] SINGLE SYMMETRY: transpose tau (x<->y), ell=m=5 "
          "(mirrors the real [[18,4,4]] code's A(x,y), B=A(y,x) structure)")
    ring = Ring(5, 5)
    A = ring.from_terms([(1, 0), (0, 2)])
    B = ring.apply_auto(A, transpose_auto())   # B(x,y) = A(y,x)
    code = BBCode(ring, A, B, name="transpose_demo")
    summarize("tau", ring, code)
    tau = transpose_auto()
    ok, info = test_code_automorphism(ring, code, tau, swap_AB=True)
    print(f"    tau with A<->B swap detected as code automorphism: {ok}")
    assert ok
    return ring, code


def example_combined_group():
    print("\n[6] MULTIPLE SYMMETRIES AT ONCE: <multiplier(2,4), theta_x> as a "
          "single generated subgroup, ell=9, m=5")
    ring = Ring(9, 5)
    psi = multiplier(9, 5, 2, 4)
    th = theta_x()
    group = group_closure([psi, th], 9, 5)
    print(f"    generated subgroup size: {len(group)}")
    A = build_orbit_poly(ring, [(1, 1)], [psi, th])
    B = build_orbit_poly(ring, [(2, 3)], [psi, th])
    code = BBCode(ring, A, B, name="combined_demo")
    summarize("combined", ring, code)
    verify_group_invariance(ring, code, [psi, th])
    return ring, code


def example_combined_ring_and_stabilizer():
    print("\n[7] VARIATION: combine a ring-level symmetry group with the free "
          "bar-involution trick, ell=8, m=6 (both even -> even x even regime)")
    ring = Ring(8, 6)
    psi = multiplier(8, 6, 3, 5)   # 3 is a unit mod 8, 5 is a unit mod 6
    A = build_orbit_poly(ring, [(1, 1)], [psi])
    B = ring.bar(A)
    code = BBCode(ring, A, B, name="combo2_demo")
    summarize("combo2", ring, code)
    verify_group_invariance(ring, code, [psi])
    ok, _ = test_code_automorphism(ring, code, full_fold(), swap_AB=True)
    print(f"    full-fold+swap (from B=bar(A)) also detected: {ok}")
    assert ok
    hits = scan_stabilizer_symmetries(ring, code, include_shears=False)
    print(f"    total full stabilizer-module symmetries found: {len(hits)}")
    return ring, code


def example_mixed_regime():
    print("\n[8] COMPLETING THE TRICHOTOMY: mixed regime (ell even, m odd), "
          "ell=8, m=5, multiplier symmetry")
    ring = Ring(8, 5)
    psi = multiplier(8, 5, 3, 2)   # ord_8(3)=2, ord_5(2)=4 -> group order 4
    A = build_orbit_poly(ring, [(1, 1)], [psi])
    B = build_orbit_poly(ring, [(0, 2)], [psi])
    code = BBCode(ring, A, B, name="mixed_demo")
    summarize("mixed", ring, code)
    verify_group_invariance(ring, code, [psi])
    return ring, code


if __name__ == "__main__":
    example_multiplier()
    example_partial_fold()
    example_full_fold_and_hadamard()
    example_shear()
    example_transpose()
    example_combined_group()
    example_combined_ring_and_stabilizer()
    example_mixed_regime()
    print("\nAll inverse-design examples verified.")
